# Generated by Django 3.2 on 2022-02-27 18:26

import adoptions.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name_text', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('adoption_date', models.DateTimeField(default=datetime.datetime(2022, 2, 27, 18, 26, 54, 119850, tzinfo=utc), verbose_name='date adopted')),
                ('adopted', models.BooleanField(default=False)),
                ('human', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('cat_photo', models.ImageField(default='static/adoptions/cat_static.jpg', upload_to=adoptions.models.rename_upload_photo)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptions.cat')),
            ],
        ),
    ]
